import { FC } from "react";
import { Typography, Card, List, Row, Col, Statistic } from "antd";
import { ImpositionResponseDto } from "../types/dto";

const { Title, Text } = Typography;

interface ILayoutResultProps {
  data: ImpositionResponseDto;
}

const LayoutGridResult: FC<ILayoutResultProps> = ({ data }) => {
  const { layout, fragments, total, garbage } = data;

  const formatNumber = (num: number, suffix: string) =>
    `${num.toFixed(4)} ${suffix}`;

  const renderLayout = (layout: ImpositionResponseDto["layout"]) => (
    <Card title="Layout Dimensions" style={{ marginBottom: 20 }}>
      <List>
        <List.Item>
          <Text strong>Width:</Text> {formatNumber(layout.width, "m")}
        </List.Item>
        <List.Item>
          <Text strong>Height:</Text> {formatNumber(layout.height, "m")}
        </List.Item>
      </List>
    </Card>
  );

  const renderFragments = (fragments: ImpositionResponseDto["fragments"]) => (
    <Card title="Fragments" style={{ marginBottom: 20 }}>
      {fragments.map((fragment, index) => (
        <List key={index}>
          <List.Item>
            <Text strong>By Width:</Text> {fragment.byWidth}
          </List.Item>
          <List.Item>
            <Text strong>By Height:</Text> {fragment.byHeight}
          </List.Item>
        </List>
      ))}
    </Card>
  );
 
  return (
    <div>
      <Title level={3}>Отрисовка раскладки на листе</Title>
      {renderLayout(layout)}
      {renderFragments(fragments)}
      <Row>
        <Col span={18} push={6}>
          col-18 col-push-6
        </Col>
        <Col span={6} pull={18}>
          col-6 col-pull-18
        </Col>
      </Row>
      
    </div>
  );
};

// Generated by Deepseek -- start
interface AreaFormat {
  width: number;
  height: number;
}

interface Element {
  width: number;
  height: number;
}

interface Distance {
  width: number;
  height: number;
}

interface Layout {
  byWidth: number;
  byHeight: number;
}

interface Fragment {
  element: Element;
  distance: Distance;
  layout: Layout;
  position: "TOP" | "BOTTOM";
}

interface TableData {
  areaFormat: AreaFormat;
  fragments: Fragment[];
}

// Функция для создания таблицы
function createTable(data: TableData): void {
  // Создаем контейнер для таблицы
  const container = document.createElement("div");
  container.style.width = `${data.areaFormat.width * 1000}px`;
  container.style.height = `${data.areaFormat.height * 1000}px`;
  container.style.border = "2px solid #000";
  container.style.display = "flex";
  container.style.flexDirection = "column";
  document.body.appendChild(container);

  // Обрабатываем каждый фрагмент
  data.fragments.forEach(fragment => {
      const section = document.createElement("div");
      section.style.display = "grid";
      section.style.gap = `${fragment.distance.width * 1000}px ${fragment.distance.height * 1000}px`;
      section.style.width = "100%";
      section.style.height = `${fragment.element.height * 1000}px`;

      // Настройка сетки в зависимости от layout
      section.style.gridTemplateColumns = `repeat(${fragment.layout.byWidth}, 1fr)`;
      section.style.gridTemplateRows = `repeat(${fragment.layout.byHeight}, 1fr)`;

      // Цвет фона для наглядности
      section.style.backgroundColor = fragment.position === "TOP" ? "#f0f0f0" : "#e0e0e0";

      // Создаем ячейки
      for (let i = 0; i < fragment.layout.byWidth * fragment.layout.byHeight; i++) {
          const cell = document.createElement("div");
          cell.style.border = "1px solid #ccc";
          cell.style.boxSizing = "border-box";
          cell.style.backgroundColor = fragment.position === "TOP" ? "#aad8ff" : "#ffcccb";
          section.appendChild(cell);
      }

      // Добавляем секцию в контейнер
      container.appendChild(section);
  });
}

// Пример JSON
const jsonData: TableData = {
  areaFormat: {
      width: 0.5,
      height: 0.3
  },
  fragments: [
      {
          element: {
              width: 0.1,
              height: 0.2
          },
          distance: {
              width: 0.002,
              height: 0.002
          },
          layout: {
              byWidth: 5,
              byHeight: 3
          },
          position: "TOP"
      },
      {
          element: {
              width: 0.2,
              height: 0.1
          },
          distance: {
              width: 0.002,
              height: 0.002
          },
          layout: {
              byWidth: 5,
              byHeight: 6
          },
          position: "BOTTOM"
      }
  ]
};

// Создаем таблицу
createTable(jsonData);
// Generated by Deepseek -- finish

export default LayoutGridResult;
